### ISSUE TITLE
poetry run db-reset issue

### ISSUE THREAD

**Issue by dpost** [101dotxyz/GPTeam#35]
Running setup.py using Python 3.8.5 on MacOS 12.6.5 fails on "poetry run db-reset"

> (base) davidlumpkin@Davids-MacBook-Pro GPTeam % python setup.py 
> Poetry is already installed.
> Installing dependencies...
> Installing dependencies from lock file
> 
> No dependencies to install or update
> 
> Installing the current project: 101-ai (0.1.0)
> Seed the database...
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/davidlumpkin/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/davidlumpkin/src/GPTeam/src/utils/database/reset.py", line 8, in <module>
>     from .seed import seed
>   File "/Users/davidlumpkin/src/GPTeam/src/utils/database/seed.py", line 5, in <module>
>     from src.utils.database.base import Tables
>   File "/Users/davidlumpkin/src/GPTeam/src/utils/database/base.py", line 22, in <module>
>     class DatabaseProviderSingleton(AbstractSingleton):
>   File "/Users/davidlumpkin/src/GPTeam/src/utils/database/base.py", line 24, in DatabaseProviderSingleton
>     async def get_by_id(self, table: Tables, id: str) -> list[dict[str, Any]]:
> TypeError: 'type' object is not subscriptable
> Traceback (most recent call last):
>   File "setup.py", line 66, in <module>
>     subprocess.run(["poetry", "run", "db-reset"], check=True)
>   File "/Users/davidlumpkin/anaconda3/lib/python3.8/subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['poetry', 'run', 'db-reset']' returned non-zero exit status 1.
> (base) davidlumpkin@Davids-MacBook-Pro GPTeam % python --version
> Python 3.8.5

**Comment by joshsny** [comment]
This is because you are running Python 3.8 which does not include support for subscriptable types.

I'll update the `pyproject.toml` to require Python >=3.9, but for now, upgrading to Python 3.9 should fix this issue.
