### ISSUE TITLE
uv loop not supporting PEP 517

### ISSUE THREAD

**Issue by anotherparadox** [101dotxyz/GPTeam#56]
apologies if this is obvious -- novice here

im on windows 11 and have been struggling to get this set up for a while

I am wondering if uv loop is necessary for everything to run or is it there solely for optimization

should I consider installing Docker or some type of linux environment? 

Thank you in advance! :)  

the error in terminal 
Note: This error originates from the build backend, and is likely not a problem with poetry but with uvloop (0.17.0) not supporting PEP 517 builds.

**Comment by Alec2435** [comment]
I'll look into whether we can drop the `uvloop` dependency, but in the meantime I recommend doing development on Windows using [Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/install).

**Comment by anotherparadox** [comment]
Thank you, ill look into that--

Running it on my mac now and it works just fine!
