### ISSUE TITLE
Always seems to say "Observed 0 events..."

### ISSUE THREAD

**Issue by derekcheungsa** [101dotxyz/GPTeam#60]
I have two people in a "Podcast studio".  But it doesn't look like they are able to see each others dialog .  For example, it always seems to say "Observed 0 events"

![image](https://github.com/101dotxyz/GPTeam/assets/122410431/3e48fe98-9221-4a82-8799-382dd56469ac)

**Comment by derekcheungsa** [comment]
Additionally, I tried to change the SerpaAPI to the GoogleSearchAPI, but neither seem to be invoked.  I tried invoking the Wolfram tool and that seems to work.

**Comment by Alec2435** [comment]
This was a bug in an earlier version, if you pull the latest changes it should be fixed
